/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TresorerieRouteImport } from './routes/tresorerie'
import { Route as SyntheseRouteImport } from './routes/synthese'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ProjectionRouteImport } from './routes/projection'
import { Route as HypothesesRouteImport } from './routes/hypotheses'
import { Route as DictionnaireRouteImport } from './routes/dictionnaire'
import { Route as DemarrageRouteImport } from './routes/demarrage'
import { Route as CompteResultatRouteImport } from './routes/compte-resultat'
import { Route as ComparaisonRouteImport } from './routes/comparaison'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const TresorerieRoute = TresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => rootRouteImport,
} as any)
const SyntheseRoute = SyntheseRouteImport.update({
  id: '/synthese',
  path: '/synthese',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionRoute = ProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const HypothesesRoute = HypothesesRouteImport.update({
  id: '/hypotheses',
  path: '/hypotheses',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionnaireRoute = DictionnaireRouteImport.update({
  id: '/dictionnaire',
  path: '/dictionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const DemarrageRoute = DemarrageRouteImport.update({
  id: '/demarrage',
  path: '/demarrage',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteResultatRoute = CompteResultatRouteImport.update({
  id: '/compte-resultat',
  path: '/compte-resultat',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparaisonRoute = ComparaisonRouteImport.update({
  id: '/comparaison',
  path: '/comparaison',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/comparaison': typeof ComparaisonRoute
  '/compte-resultat': typeof CompteResultatRoute
  '/demarrage': typeof DemarrageRoute
  '/dictionnaire': typeof DictionnaireRoute
  '/hypotheses': typeof HypothesesRoute
  '/projection': typeof ProjectionRoute
  '/scenarios': typeof ScenariosRoute
  '/synthese': typeof SyntheseRoute
  '/tresorerie': typeof TresorerieRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/comparaison': typeof ComparaisonRoute
  '/compte-resultat': typeof CompteResultatRoute
  '/demarrage': typeof DemarrageRoute
  '/dictionnaire': typeof DictionnaireRoute
  '/hypotheses': typeof HypothesesRoute
  '/projection': typeof ProjectionRoute
  '/scenarios': typeof ScenariosRoute
  '/synthese': typeof SyntheseRoute
  '/tresorerie': typeof TresorerieRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/comparaison': typeof ComparaisonRoute
  '/compte-resultat': typeof CompteResultatRoute
  '/demarrage': typeof DemarrageRoute
  '/dictionnaire': typeof DictionnaireRoute
  '/hypotheses': typeof HypothesesRoute
  '/projection': typeof ProjectionRoute
  '/scenarios': typeof ScenariosRoute
  '/synthese': typeof SyntheseRoute
  '/tresorerie': typeof TresorerieRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/comparaison'
    | '/compte-resultat'
    | '/demarrage'
    | '/dictionnaire'
    | '/hypotheses'
    | '/projection'
    | '/scenarios'
    | '/synthese'
    | '/tresorerie'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business'
    | '/comparaison'
    | '/compte-resultat'
    | '/demarrage'
    | '/dictionnaire'
    | '/hypotheses'
    | '/projection'
    | '/scenarios'
    | '/synthese'
    | '/tresorerie'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/comparaison'
    | '/compte-resultat'
    | '/demarrage'
    | '/dictionnaire'
    | '/hypotheses'
    | '/projection'
    | '/scenarios'
    | '/synthese'
    | '/tresorerie'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  ComparaisonRoute: typeof ComparaisonRoute
  CompteResultatRoute: typeof CompteResultatRoute
  DemarrageRoute: typeof DemarrageRoute
  DictionnaireRoute: typeof DictionnaireRoute
  HypothesesRoute: typeof HypothesesRoute
  ProjectionRoute: typeof ProjectionRoute
  ScenariosRoute: typeof ScenariosRoute
  SyntheseRoute: typeof SyntheseRoute
  TresorerieRoute: typeof TresorerieRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tresorerie': {
      id: '/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof TresorerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthese': {
      id: '/synthese'
      path: '/synthese'
      fullPath: '/synthese'
      preLoaderRoute: typeof SyntheseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projection': {
      id: '/projection'
      path: '/projection'
      fullPath: '/projection'
      preLoaderRoute: typeof ProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hypotheses': {
      id: '/hypotheses'
      path: '/hypotheses'
      fullPath: '/hypotheses'
      preLoaderRoute: typeof HypothesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionnaire': {
      id: '/dictionnaire'
      path: '/dictionnaire'
      fullPath: '/dictionnaire'
      preLoaderRoute: typeof DictionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demarrage': {
      id: '/demarrage'
      path: '/demarrage'
      fullPath: '/demarrage'
      preLoaderRoute: typeof DemarrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte-resultat': {
      id: '/compte-resultat'
      path: '/compte-resultat'
      fullPath: '/compte-resultat'
      preLoaderRoute: typeof CompteResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparaison': {
      id: '/comparaison'
      path: '/comparaison'
      fullPath: '/comparaison'
      preLoaderRoute: typeof ComparaisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  ComparaisonRoute: ComparaisonRoute,
  CompteResultatRoute: CompteResultatRoute,
  DemarrageRoute: DemarrageRoute,
  DictionnaireRoute: DictionnaireRoute,
  HypothesesRoute: HypothesesRoute,
  ProjectionRoute: ProjectionRoute,
  ScenariosRoute: ScenariosRoute,
  SyntheseRoute: SyntheseRoute,
  TresorerieRoute: TresorerieRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
